// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr55VaPkzV5zZiC-1QKQtrPvH3B1v-ea4',
    appId: '1:955879744574:web:eb4af64484d6657d5f5d6f',
    messagingSenderId: '955879744574',
    projectId: 'event-app-4cde6',
    authDomain: 'event-app-4cde6.firebaseapp.com',
    storageBucket: 'event-app-4cde6.firebasestorage.app',
    measurementId: 'G-4QP9DK2WWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM9Y1TYT1ZFSWnteCILR2eNd9axSRIloM',
    appId: '1:955879744574:android:054234af30f935b45f5d6f',
    messagingSenderId: '955879744574',
    projectId: 'event-app-4cde6',
    storageBucket: 'event-app-4cde6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuobDPb7qgw0dq1rXG9DbW-kRwZujfSxk',
    appId: '1:955879744574:ios:ed4b9e91a5c2ac305f5d6f',
    messagingSenderId: '955879744574',
    projectId: 'event-app-4cde6',
    storageBucket: 'event-app-4cde6.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuobDPb7qgw0dq1rXG9DbW-kRwZujfSxk',
    appId: '1:955879744574:ios:ed4b9e91a5c2ac305f5d6f',
    messagingSenderId: '955879744574',
    projectId: 'event-app-4cde6',
    storageBucket: 'event-app-4cde6.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr55VaPkzV5zZiC-1QKQtrPvH3B1v-ea4',
    appId: '1:955879744574:web:9fa7c7f13f05d1215f5d6f',
    messagingSenderId: '955879744574',
    projectId: 'event-app-4cde6',
    authDomain: 'event-app-4cde6.firebaseapp.com',
    storageBucket: 'event-app-4cde6.firebasestorage.app',
    measurementId: 'G-Y8S57XBW66',
  );
}
